language: nl
charset: utf-8
site:
    title: Aniridie België
    description: Een groep voor en door Belgische aniridie patiënten
menu:
    -
        name: Start
        description: Start pagina
        css_class: home
        type: page
        url: index.html
    -
        name: Nieuws
        description: Nieuws
        css_class: blog
        type: node
        url: news
    -
        name: Info
        description: info
        css_class: info
        type: node
        url: info
    -
        name: Over ons
        description: Over ons
        css_class: about
        type: page
        url: about.html
